Fix Django template error - use 'id' instead of '_id'
Error: Variables and attributes may not begin with underscores
Cause: Django templates don't allow {{ printer._id }}

Solution:
- Changed {{ printer._id }} to {{ printer.id }}

The doc_to_dict() function already converts MongoDB's _id to id:
  doc['id'] = str(doc['_id'])

So we just use the converted 'id' field in templates.

Fixed in all places:
- Edit link href
- showModeChangeModal() onclick
- deletePrinter() onclick